spring.application.name=code

management.endpoint.health.show-details=always
management.health.db.enabled=true

spring.datasource.url=jdbc:mysql://172.21.71.58/inventory?usessl=false
spring.datasource.username=root
spring.datasource.password=5vuJhLzLon72ku0r8BDh2sLT
spring.data.mongodb.uri=mongodb://root:x8a51zYHZHMODD22WTJxstYY@172.21.2.249:27017/library?authSource=admin