spring.application.name=code

management.endpoint.health.show-details=always
management.health.db.enabled=true

spring.datasource.url=jdbc:mysql://172.21.29.182/inventory?usessl=false
spring.datasource.username=root
spring.datasource.password=8bHZuST1bnvp0XBNpedW5hdE
spring.data.mongodb.uri=mongodb://root:iBsIX8UAKb1zL6okT5nzD9T6@172.21.36.94:27017/library?authSource=admin